### ISSUE TITLE
"target_link_options" not highlighted as command

### ISSUE THREAD

**Issue by tdegeus** [zyxar/Sublime-CMakeLists#36]
The command "target_link_options" is not highlighted as such.

**Comment by rwols** [comment]
target_link_options receives `variable.function`, which should be the same color as `support.function`. Check your color scheme if it colors those scopes the same. `support.function` is supposed to be for built-ins, while `variable.function` is supposed to be for arbitrary functions. The error in the syntax is that it should get updated to make target_link_options a built-in command, instead of a user-defined command.

**Comment by tdegeus** [comment]
So this is wanted behaviour?

**Comment by rwols** [comment]
No, it's a command that has recently been added as a built-in to cmake, so this syntax should get an update too. The syntax is outdated.

However what you can do in the meantime is make sure that your color scheme is behaving correctly by checking wether the scope `variable.function` is roughly colored the same as the scope `support.function`.

target_link_options is currently considered a user-defined function, as if it was defined by

```
function(target_link_options)
  # ...
endfunction()
```

All these user-defined functions receive the `variable.function` scope. Monokai and Mariana colors those two scopes the same, and the [scope naming guide](https://www.sublimetext.com/docs/3/scope_naming.html#color_schemes) also tells us that

> The name of the function or method should be variable.function, unless the function is scoped with support.function

**Comment by tdegeus** [comment]
Clear! Thanks!
